FORMAT: 1A
HOST: http://bestwest.apiblueprint.org/

# BestWest API

This is where 600 West tenants can find the best way to get to and from the office.

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "How should I transport myself?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "options": [
                    {
                        "direction": "westbound",
                        "pickupLocation": "brown",
                        "transpoMethod": "CTABus",
                        "pickupTime": "8:30am"
                    }, {
                        "direction": "eastbound",
                        "pickupLocation": "brown",
                        "transpoMethod": "CTABus",
                        "pickupTime": "8:30am"                    
                    }, {
                       "direction": "westbound",
                        "pickupLocation": "brown",
                        "transpoMethod": "shuttleBus",
                        "pickupTime": "8:30am"
                    }, {
                        "direction": "eastbound",
                        "pickupLocation": "brown",
                        "transpoMethod": "shuttleBus",
                        "pickupTime": "8:30am"
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "How should I transport myself?",
            "options": [
                "CTABus",
                "shuttleBus"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "How should I transport myself",
                "published_at": "2015-08-05T08:40:51.620Z",
                "options": [
                    {
                        "direction": "westbound",
                        "pickupLocation": "brown",
                        "transpoMethod": "CTABus",
                        "pickupTime": "8:30am"
                    }, {
                        "direction": "eastbound",
                        "pickupLocation": "brown",
                        "transpoMethod": "CTABus",
                        "pickupTime": "8:30am"                    
                    }, {
                       "direction": "westbound",
                        "pickupLocation": "brown",
                        "transpoMethod": "shuttleBus",
                        "pickupTime": "8:30am"
                    }, {
                        "direction": "eastbound",
                        "pickupLocation": "brown",
                        "transpoMethod": "shuttleBus",
                        "pickupTime": "8:30am"
                    }
                ]
            }